// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string zipcode = 1;</code>
   * @return The zipcode.
   */
  java.lang.String getZipcode();
  /**
   * <code>string zipcode = 1;</code>
   * @return The bytes for zipcode.
   */
  com.google.protobuf.ByteString
      getZipcodeBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>double qkm = 3;</code>
   * @return The qkm.
   */
  double getQkm();

  /**
   * <code>int32 population = 4;</code>
   * @return The population.
   */
  int getPopulation();

  /**
   * <code>repeated .Challenger.Polygon polygons = 5;</code>
   */
  java.util.List<com.grpc.Polygon> 
      getPolygonsList();
  /**
   * <code>repeated .Challenger.Polygon polygons = 5;</code>
   */
  com.grpc.Polygon getPolygons(int index);
  /**
   * <code>repeated .Challenger.Polygon polygons = 5;</code>
   */
  int getPolygonsCount();
  /**
   * <code>repeated .Challenger.Polygon polygons = 5;</code>
   */
  java.util.List<? extends com.grpc.PolygonOrBuilder> 
      getPolygonsOrBuilderList();
  /**
   * <code>repeated .Challenger.Polygon polygons = 5;</code>
   */
  com.grpc.PolygonOrBuilder getPolygonsOrBuilder(
      int index);
}
