// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface LocationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Locations)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  java.util.List<com.grpc.Location> 
      getLocationsList();
  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  com.grpc.Location getLocations(int index);
  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  int getLocationsCount();
  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  java.util.List<? extends com.grpc.LocationOrBuilder> 
      getLocationsOrBuilderList();
  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  com.grpc.LocationOrBuilder getLocationsOrBuilder(
      int index);
}
