// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface MeasurementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Measurement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>float latitude = 2;</code>
   * @return The latitude.
   */
  float getLatitude();

  /**
   * <code>float longitude = 3;</code>
   * @return The longitude.
   */
  float getLongitude();

  /**
   * <pre>
   *Particles &lt; 10µm (particulate matter)
   * </pre>
   *
   * <code>float p1 = 4;</code>
   * @return The p1.
   */
  float getP1();

  /**
   * <pre>
   *Particles &lt; 2.5µm (ultrafine particles)
   * </pre>
   *
   * <code>float p2 = 5;</code>
   * @return The p2.
   */
  float getP2();
}
