// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double longitude = 1;</code>
   * @return The longitude.
   */
  double getLongitude();

  /**
   * <code>double latitude = 2;</code>
   * @return The latitude.
   */
  double getLatitude();
}
