// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface TopKCitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.TopKCities)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 position = 1;</code>
   * @return The position.
   */
  int getPosition();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>int32 averageAQIImprovement = 3;</code>
   * @return The averageAQIImprovement.
   */
  int getAverageAQIImprovement();

  /**
   * <code>int32 currentAQIP1 = 5;</code>
   * @return The currentAQIP1.
   */
  int getCurrentAQIP1();

  /**
   * <code>int32 currentAQIP2 = 6;</code>
   * @return The currentAQIP2.
   */
  int getCurrentAQIP2();
}
