// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface BatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Batch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 seq_id = 1;</code>
   * @return The seqId.
   */
  long getSeqId();

  /**
   * <pre>
   *Set to true when it is the last batch
   * </pre>
   *
   * <code>bool last = 2;</code>
   * @return The last.
   */
  boolean getLast();

  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  java.util.List<com.grpc.Measurement> 
      getCurrentList();
  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  com.grpc.Measurement getCurrent(int index);
  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  int getCurrentCount();
  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  java.util.List<? extends com.grpc.MeasurementOrBuilder> 
      getCurrentOrBuilderList();
  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  com.grpc.MeasurementOrBuilder getCurrentOrBuilder(
      int index);

  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  java.util.List<com.grpc.Measurement> 
      getLastyearList();
  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  com.grpc.Measurement getLastyear(int index);
  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  int getLastyearCount();
  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  java.util.List<? extends com.grpc.MeasurementOrBuilder> 
      getLastyearOrBuilderList();
  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  com.grpc.MeasurementOrBuilder getLastyearOrBuilder(
      int index);
}
