// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public final class ChallengerProto {
  private ChallengerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_Measurement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_Measurement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_Batch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_Batch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_Benchmark_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_Benchmark_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_TopKCities_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_TopKCities_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_ResultQ1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_ResultQ1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_TopKStreaks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_TopKStreaks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_ResultQ2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_ResultQ2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_BenchmarkConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_BenchmarkConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_Polygon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_Polygon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Challenger_Locations_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Challenger_Locations_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020challenger.proto\022\nChallenger\032\033google/p" +
      "rotobuf/empty.proto\032\037google/protobuf/tim" +
      "estamp.proto\"y\n\013Measurement\022-\n\ttimestamp" +
      "\030\001 \001(\0132\032.google.protobuf.Timestamp\022\020\n\010la" +
      "titude\030\002 \001(\002\022\021\n\tlongitude\030\003 \001(\002\022\n\n\002p1\030\004 " +
      "\001(\002\022\n\n\002p2\030\005 \001(\002\"z\n\005Batch\022\016\n\006seq_id\030\001 \001(\003" +
      "\022\014\n\004last\030\002 \001(\010\022(\n\007current\030\003 \003(\0132\027.Challe" +
      "nger.Measurement\022)\n\010lastyear\030\004 \003(\0132\027.Cha" +
      "llenger.Measurement\"\027\n\tBenchmark\022\n\n\002id\030\001" +
      " \001(\003\"w\n\nTopKCities\022\020\n\010position\030\001 \001(\005\022\014\n\004" +
      "city\030\002 \001(\t\022\035\n\025averageAQIImprovement\030\003 \001(" +
      "\005\022\024\n\014currentAQIP1\030\005 \001(\005\022\024\n\014currentAQIP2\030" +
      "\006 \001(\005\"d\n\010ResultQ1\022\024\n\014benchmark_id\030\001 \001(\003\022" +
      "\024\n\014batch_seq_id\030\002 \001(\003\022,\n\014topkimproved\030\003 " +
      "\003(\0132\026.Challenger.TopKCities\"M\n\013TopKStrea" +
      "ks\022\023\n\013bucket_from\030\001 \001(\005\022\021\n\tbucket_to\030\002 \001" +
      "(\005\022\026\n\016bucket_percent\030\003 \001(\005\"b\n\010ResultQ2\022\024" +
      "\n\014benchmark_id\030\001 \001(\003\022\024\n\014batch_seq_id\030\002 \001" +
      "(\003\022*\n\thistogram\030\003 \003(\0132\027.Challenger.TopKS" +
      "treaks\"4\n\004Ping\022\024\n\014benchmark_id\030\001 \001(\003\022\026\n\016" +
      "correlation_id\030\002 \001(\003\"\277\001\n\026BenchmarkConfig" +
      "uration\022\r\n\005token\030\001 \001(\t\022\022\n\nbatch_size\030\002 \001" +
      "(\005\022\026\n\016benchmark_name\030\003 \001(\t\022\026\n\016benchmark_" +
      "type\030\004 \001(\t\0229\n\007queries\030\005 \003(\0162(.Challenger" +
      ".BenchmarkConfiguration.Query\"\027\n\005Query\022\006" +
      "\n\002Q1\020\000\022\006\n\002Q2\020\001\",\n\005Point\022\021\n\tlongitude\030\001 \001" +
      "(\001\022\020\n\010latitude\030\002 \001(\001\",\n\007Polygon\022!\n\006point" +
      "s\030\001 \003(\0132\021.Challenger.Point\"q\n\010Location\022\017" +
      "\n\007zipcode\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\013\n\003qkm\030\003 \001" +
      "(\001\022\022\n\npopulation\030\004 \001(\005\022%\n\010polygons\030\005 \003(\013" +
      "2\023.Challenger.Polygon\"4\n\tLocations\022\'\n\tlo" +
      "cations\030\001 \003(\0132\024.Challenger.Location2\370\004\n\n" +
      "Challenger\022O\n\022createNewBenchmark\022\".Chall" +
      "enger.BenchmarkConfiguration\032\025.Challenge" +
      "r.Benchmark\022<\n\014getLocations\022\025.Challenger" +
      ".Benchmark\032\025.Challenger.Locations\022E\n\032ini" +
      "tializeLatencyMeasuring\022\025.Challenger.Ben" +
      "chmark\032\020.Challenger.Ping\022-\n\007measure\022\020.Ch" +
      "allenger.Ping\032\020.Challenger.Ping\022:\n\016endMe" +
      "asurement\022\020.Challenger.Ping\032\026.google.pro" +
      "tobuf.Empty\022?\n\016startBenchmark\022\025.Challeng" +
      "er.Benchmark\032\026.google.protobuf.Empty\0225\n\t" +
      "nextBatch\022\025.Challenger.Benchmark\032\021.Chall" +
      "enger.Batch\0228\n\010resultQ1\022\024.Challenger.Res" +
      "ultQ1\032\026.google.protobuf.Empty\0228\n\010resultQ" +
      "2\022\024.Challenger.ResultQ2\032\026.google.protobu" +
      "f.Empty\022=\n\014endBenchmark\022\025.Challenger.Ben" +
      "chmark\032\026.google.protobuf.EmptyB\035\n\010com.gr" +
      "pcB\017ChallengerProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Challenger_Measurement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Challenger_Measurement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_Measurement_descriptor,
        new java.lang.String[] { "Timestamp", "Latitude", "Longitude", "P1", "P2", });
    internal_static_Challenger_Batch_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Challenger_Batch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_Batch_descriptor,
        new java.lang.String[] { "SeqId", "Last", "Current", "Lastyear", });
    internal_static_Challenger_Benchmark_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Challenger_Benchmark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_Benchmark_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Challenger_TopKCities_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Challenger_TopKCities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_TopKCities_descriptor,
        new java.lang.String[] { "Position", "City", "AverageAQIImprovement", "CurrentAQIP1", "CurrentAQIP2", });
    internal_static_Challenger_ResultQ1_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Challenger_ResultQ1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_ResultQ1_descriptor,
        new java.lang.String[] { "BenchmarkId", "BatchSeqId", "Topkimproved", });
    internal_static_Challenger_TopKStreaks_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Challenger_TopKStreaks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_TopKStreaks_descriptor,
        new java.lang.String[] { "BucketFrom", "BucketTo", "BucketPercent", });
    internal_static_Challenger_ResultQ2_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Challenger_ResultQ2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_ResultQ2_descriptor,
        new java.lang.String[] { "BenchmarkId", "BatchSeqId", "Histogram", });
    internal_static_Challenger_Ping_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Challenger_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_Ping_descriptor,
        new java.lang.String[] { "BenchmarkId", "CorrelationId", });
    internal_static_Challenger_BenchmarkConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Challenger_BenchmarkConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_BenchmarkConfiguration_descriptor,
        new java.lang.String[] { "Token", "BatchSize", "BenchmarkName", "BenchmarkType", "Queries", });
    internal_static_Challenger_Point_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Challenger_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_Point_descriptor,
        new java.lang.String[] { "Longitude", "Latitude", });
    internal_static_Challenger_Polygon_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Challenger_Polygon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_Polygon_descriptor,
        new java.lang.String[] { "Points", });
    internal_static_Challenger_Location_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Challenger_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_Location_descriptor,
        new java.lang.String[] { "Zipcode", "City", "Qkm", "Population", "Polygons", });
    internal_static_Challenger_Locations_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Challenger_Locations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Challenger_Locations_descriptor,
        new java.lang.String[] { "Locations", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
