// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Ping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 benchmark_id = 1;</code>
   * @return The benchmarkId.
   */
  long getBenchmarkId();

  /**
   * <code>int64 correlation_id = 2;</code>
   * @return The correlationId.
   */
  long getCorrelationId();
}
