// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface ResultQ2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.ResultQ2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 benchmark_id = 1;</code>
   * @return The benchmarkId.
   */
  long getBenchmarkId();

  /**
   * <code>int64 batch_seq_id = 2;</code>
   * @return The batchSeqId.
   */
  long getBatchSeqId();

  /**
   * <code>repeated .Challenger.TopKStreaks histogram = 3;</code>
   */
  java.util.List<com.grpc.TopKStreaks> 
      getHistogramList();
  /**
   * <code>repeated .Challenger.TopKStreaks histogram = 3;</code>
   */
  com.grpc.TopKStreaks getHistogram(int index);
  /**
   * <code>repeated .Challenger.TopKStreaks histogram = 3;</code>
   */
  int getHistogramCount();
  /**
   * <code>repeated .Challenger.TopKStreaks histogram = 3;</code>
   */
  java.util.List<? extends com.grpc.TopKStreaksOrBuilder> 
      getHistogramOrBuilderList();
  /**
   * <code>repeated .Challenger.TopKStreaks histogram = 3;</code>
   */
  com.grpc.TopKStreaksOrBuilder getHistogramOrBuilder(
      int index);
}
