// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

/**
 * Protobuf type {@code Challenger.TopKCities}
 */
public  final class TopKCities extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Challenger.TopKCities)
    TopKCitiesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TopKCities.newBuilder() to construct.
  private TopKCities(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopKCities() {
    city_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TopKCities();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TopKCities(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            position_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 24: {

            averageAQIImprovement_ = input.readInt32();
            break;
          }
          case 40: {

            currentAQIP1_ = input.readInt32();
            break;
          }
          case 48: {

            currentAQIP2_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.ChallengerProto.internal_static_Challenger_TopKCities_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.ChallengerProto.internal_static_Challenger_TopKCities_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.TopKCities.class, com.grpc.TopKCities.Builder.class);
  }

  public static final int POSITION_FIELD_NUMBER = 1;
  private int position_;
  /**
   * <code>int32 position = 1;</code>
   * @return The position.
   */
  public int getPosition() {
    return position_;
  }

  public static final int CITY_FIELD_NUMBER = 2;
  private volatile java.lang.Object city_;
  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVERAGEAQIIMPROVEMENT_FIELD_NUMBER = 3;
  private int averageAQIImprovement_;
  /**
   * <code>int32 averageAQIImprovement = 3;</code>
   * @return The averageAQIImprovement.
   */
  public int getAverageAQIImprovement() {
    return averageAQIImprovement_;
  }

  public static final int CURRENTAQIP1_FIELD_NUMBER = 5;
  private int currentAQIP1_;
  /**
   * <code>int32 currentAQIP1 = 5;</code>
   * @return The currentAQIP1.
   */
  public int getCurrentAQIP1() {
    return currentAQIP1_;
  }

  public static final int CURRENTAQIP2_FIELD_NUMBER = 6;
  private int currentAQIP2_;
  /**
   * <code>int32 currentAQIP2 = 6;</code>
   * @return The currentAQIP2.
   */
  public int getCurrentAQIP2() {
    return currentAQIP2_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (position_ != 0) {
      output.writeInt32(1, position_);
    }
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
    }
    if (averageAQIImprovement_ != 0) {
      output.writeInt32(3, averageAQIImprovement_);
    }
    if (currentAQIP1_ != 0) {
      output.writeInt32(5, currentAQIP1_);
    }
    if (currentAQIP2_ != 0) {
      output.writeInt32(6, currentAQIP2_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (position_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, position_);
    }
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
    }
    if (averageAQIImprovement_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, averageAQIImprovement_);
    }
    if (currentAQIP1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, currentAQIP1_);
    }
    if (currentAQIP2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, currentAQIP2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.TopKCities)) {
      return super.equals(obj);
    }
    com.grpc.TopKCities other = (com.grpc.TopKCities) obj;

    if (getPosition()
        != other.getPosition()) return false;
    if (!getCity()
        .equals(other.getCity())) return false;
    if (getAverageAQIImprovement()
        != other.getAverageAQIImprovement()) return false;
    if (getCurrentAQIP1()
        != other.getCurrentAQIP1()) return false;
    if (getCurrentAQIP2()
        != other.getCurrentAQIP2()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getPosition();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + AVERAGEAQIIMPROVEMENT_FIELD_NUMBER;
    hash = (53 * hash) + getAverageAQIImprovement();
    hash = (37 * hash) + CURRENTAQIP1_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentAQIP1();
    hash = (37 * hash) + CURRENTAQIP2_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentAQIP2();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.TopKCities parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.TopKCities parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.TopKCities parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.TopKCities parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.TopKCities parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.TopKCities parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.TopKCities parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.TopKCities parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.TopKCities parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.TopKCities parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.TopKCities parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.TopKCities parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.TopKCities prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Challenger.TopKCities}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Challenger.TopKCities)
      com.grpc.TopKCitiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.ChallengerProto.internal_static_Challenger_TopKCities_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.ChallengerProto.internal_static_Challenger_TopKCities_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.TopKCities.class, com.grpc.TopKCities.Builder.class);
    }

    // Construct using com.grpc.TopKCities.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      position_ = 0;

      city_ = "";

      averageAQIImprovement_ = 0;

      currentAQIP1_ = 0;

      currentAQIP2_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.ChallengerProto.internal_static_Challenger_TopKCities_descriptor;
    }

    @java.lang.Override
    public com.grpc.TopKCities getDefaultInstanceForType() {
      return com.grpc.TopKCities.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.TopKCities build() {
      com.grpc.TopKCities result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.TopKCities buildPartial() {
      com.grpc.TopKCities result = new com.grpc.TopKCities(this);
      result.position_ = position_;
      result.city_ = city_;
      result.averageAQIImprovement_ = averageAQIImprovement_;
      result.currentAQIP1_ = currentAQIP1_;
      result.currentAQIP2_ = currentAQIP2_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.TopKCities) {
        return mergeFrom((com.grpc.TopKCities)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.TopKCities other) {
      if (other == com.grpc.TopKCities.getDefaultInstance()) return this;
      if (other.getPosition() != 0) {
        setPosition(other.getPosition());
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (other.getAverageAQIImprovement() != 0) {
        setAverageAQIImprovement(other.getAverageAQIImprovement());
      }
      if (other.getCurrentAQIP1() != 0) {
        setCurrentAQIP1(other.getCurrentAQIP1());
      }
      if (other.getCurrentAQIP2() != 0) {
        setCurrentAQIP2(other.getCurrentAQIP2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.TopKCities parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.TopKCities) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int position_ ;
    /**
     * <code>int32 position = 1;</code>
     * @return The position.
     */
    public int getPosition() {
      return position_;
    }
    /**
     * <code>int32 position = 1;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(int value) {
      
      position_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 position = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      
      position_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>string city = 2;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private int averageAQIImprovement_ ;
    /**
     * <code>int32 averageAQIImprovement = 3;</code>
     * @return The averageAQIImprovement.
     */
    public int getAverageAQIImprovement() {
      return averageAQIImprovement_;
    }
    /**
     * <code>int32 averageAQIImprovement = 3;</code>
     * @param value The averageAQIImprovement to set.
     * @return This builder for chaining.
     */
    public Builder setAverageAQIImprovement(int value) {
      
      averageAQIImprovement_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 averageAQIImprovement = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAverageAQIImprovement() {
      
      averageAQIImprovement_ = 0;
      onChanged();
      return this;
    }

    private int currentAQIP1_ ;
    /**
     * <code>int32 currentAQIP1 = 5;</code>
     * @return The currentAQIP1.
     */
    public int getCurrentAQIP1() {
      return currentAQIP1_;
    }
    /**
     * <code>int32 currentAQIP1 = 5;</code>
     * @param value The currentAQIP1 to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentAQIP1(int value) {
      
      currentAQIP1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentAQIP1 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentAQIP1() {
      
      currentAQIP1_ = 0;
      onChanged();
      return this;
    }

    private int currentAQIP2_ ;
    /**
     * <code>int32 currentAQIP2 = 6;</code>
     * @return The currentAQIP2.
     */
    public int getCurrentAQIP2() {
      return currentAQIP2_;
    }
    /**
     * <code>int32 currentAQIP2 = 6;</code>
     * @param value The currentAQIP2 to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentAQIP2(int value) {
      
      currentAQIP2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentAQIP2 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentAQIP2() {
      
      currentAQIP2_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Challenger.TopKCities)
  }

  // @@protoc_insertion_point(class_scope:Challenger.TopKCities)
  private static final com.grpc.TopKCities DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.TopKCities();
  }

  public static com.grpc.TopKCities getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopKCities>
      PARSER = new com.google.protobuf.AbstractParser<TopKCities>() {
    @java.lang.Override
    public TopKCities parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TopKCities(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TopKCities> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TopKCities> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.TopKCities getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

