// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package de.tum.i13.bandency;

public interface BatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Batch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 seq_id = 1;</code>
   * @return The seqId.
   */
  long getSeqId();

  /**
   * <pre>
   *Set to true when it is the last batch
   * </pre>
   *
   * <code>bool last = 2;</code>
   * @return The last.
   */
  boolean getLast();

  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  java.util.List<de.tum.i13.bandency.Measurement> 
      getCurrentList();
  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  de.tum.i13.bandency.Measurement getCurrent(int index);
  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  int getCurrentCount();
  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  java.util.List<? extends de.tum.i13.bandency.MeasurementOrBuilder> 
      getCurrentOrBuilderList();
  /**
   * <code>repeated .Challenger.Measurement current = 3;</code>
   */
  de.tum.i13.bandency.MeasurementOrBuilder getCurrentOrBuilder(
      int index);

  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  java.util.List<de.tum.i13.bandency.Measurement> 
      getLastyearList();
  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  de.tum.i13.bandency.Measurement getLastyear(int index);
  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  int getLastyearCount();
  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  java.util.List<? extends de.tum.i13.bandency.MeasurementOrBuilder> 
      getLastyearOrBuilderList();
  /**
   * <code>repeated .Challenger.Measurement lastyear = 4;</code>
   */
  de.tum.i13.bandency.MeasurementOrBuilder getLastyearOrBuilder(
      int index);
}
