// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package de.tum.i13.bandency;

public interface LocationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Locations)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  java.util.List<de.tum.i13.bandency.Location> 
      getLocationsList();
  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  de.tum.i13.bandency.Location getLocations(int index);
  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  int getLocationsCount();
  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  java.util.List<? extends de.tum.i13.bandency.LocationOrBuilder> 
      getLocationsOrBuilderList();
  /**
   * <code>repeated .Challenger.Location locations = 1;</code>
   */
  de.tum.i13.bandency.LocationOrBuilder getLocationsOrBuilder(
      int index);
}
