// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package de.tum.i13.bandency;

public interface PolygonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Polygon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Challenger.Point points = 1;</code>
   */
  java.util.List<de.tum.i13.bandency.Point> 
      getPointsList();
  /**
   * <code>repeated .Challenger.Point points = 1;</code>
   */
  de.tum.i13.bandency.Point getPoints(int index);
  /**
   * <code>repeated .Challenger.Point points = 1;</code>
   */
  int getPointsCount();
  /**
   * <code>repeated .Challenger.Point points = 1;</code>
   */
  java.util.List<? extends de.tum.i13.bandency.PointOrBuilder> 
      getPointsOrBuilderList();
  /**
   * <code>repeated .Challenger.Point points = 1;</code>
   */
  de.tum.i13.bandency.PointOrBuilder getPointsOrBuilder(
      int index);
}
