// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package de.tum.i13.bandency;

/**
 * Protobuf type {@code Challenger.TopKStreaks}
 */
public  final class TopKStreaks extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Challenger.TopKStreaks)
    TopKStreaksOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TopKStreaks.newBuilder() to construct.
  private TopKStreaks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopKStreaks() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TopKStreaks();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TopKStreaks(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            bucketFrom_ = input.readInt32();
            break;
          }
          case 16: {

            bucketTo_ = input.readInt32();
            break;
          }
          case 24: {

            bucketPercent_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.tum.i13.bandency.ChallengerProto.internal_static_Challenger_TopKStreaks_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.tum.i13.bandency.ChallengerProto.internal_static_Challenger_TopKStreaks_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.tum.i13.bandency.TopKStreaks.class, de.tum.i13.bandency.TopKStreaks.Builder.class);
  }

  public static final int BUCKET_FROM_FIELD_NUMBER = 1;
  private int bucketFrom_;
  /**
   * <pre>
   *begin of the bucket
   * </pre>
   *
   * <code>int32 bucket_from = 1;</code>
   * @return The bucketFrom.
   */
  public int getBucketFrom() {
    return bucketFrom_;
  }

  public static final int BUCKET_TO_FIELD_NUMBER = 2;
  private int bucketTo_;
  /**
   * <pre>
   *end of the bucket
   * </pre>
   *
   * <code>int32 bucket_to = 2;</code>
   * @return The bucketTo.
   */
  public int getBucketTo() {
    return bucketTo_;
  }

  public static final int BUCKET_PERCENT_FIELD_NUMBER = 3;
  private int bucketPercent_;
  /**
   * <pre>
   *round(float, 3) * 1000 as integer
   * </pre>
   *
   * <code>int32 bucket_percent = 3;</code>
   * @return The bucketPercent.
   */
  public int getBucketPercent() {
    return bucketPercent_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bucketFrom_ != 0) {
      output.writeInt32(1, bucketFrom_);
    }
    if (bucketTo_ != 0) {
      output.writeInt32(2, bucketTo_);
    }
    if (bucketPercent_ != 0) {
      output.writeInt32(3, bucketPercent_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bucketFrom_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, bucketFrom_);
    }
    if (bucketTo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, bucketTo_);
    }
    if (bucketPercent_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, bucketPercent_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.tum.i13.bandency.TopKStreaks)) {
      return super.equals(obj);
    }
    de.tum.i13.bandency.TopKStreaks other = (de.tum.i13.bandency.TopKStreaks) obj;

    if (getBucketFrom()
        != other.getBucketFrom()) return false;
    if (getBucketTo()
        != other.getBucketTo()) return false;
    if (getBucketPercent()
        != other.getBucketPercent()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUCKET_FROM_FIELD_NUMBER;
    hash = (53 * hash) + getBucketFrom();
    hash = (37 * hash) + BUCKET_TO_FIELD_NUMBER;
    hash = (53 * hash) + getBucketTo();
    hash = (37 * hash) + BUCKET_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + getBucketPercent();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.tum.i13.bandency.TopKStreaks parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.tum.i13.bandency.TopKStreaks parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.tum.i13.bandency.TopKStreaks parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.tum.i13.bandency.TopKStreaks parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.tum.i13.bandency.TopKStreaks prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Challenger.TopKStreaks}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Challenger.TopKStreaks)
      de.tum.i13.bandency.TopKStreaksOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.tum.i13.bandency.ChallengerProto.internal_static_Challenger_TopKStreaks_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.tum.i13.bandency.ChallengerProto.internal_static_Challenger_TopKStreaks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.tum.i13.bandency.TopKStreaks.class, de.tum.i13.bandency.TopKStreaks.Builder.class);
    }

    // Construct using de.tum.i13.bandency.TopKStreaks.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bucketFrom_ = 0;

      bucketTo_ = 0;

      bucketPercent_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.tum.i13.bandency.ChallengerProto.internal_static_Challenger_TopKStreaks_descriptor;
    }

    @java.lang.Override
    public de.tum.i13.bandency.TopKStreaks getDefaultInstanceForType() {
      return de.tum.i13.bandency.TopKStreaks.getDefaultInstance();
    }

    @java.lang.Override
    public de.tum.i13.bandency.TopKStreaks build() {
      de.tum.i13.bandency.TopKStreaks result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.tum.i13.bandency.TopKStreaks buildPartial() {
      de.tum.i13.bandency.TopKStreaks result = new de.tum.i13.bandency.TopKStreaks(this);
      result.bucketFrom_ = bucketFrom_;
      result.bucketTo_ = bucketTo_;
      result.bucketPercent_ = bucketPercent_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.tum.i13.bandency.TopKStreaks) {
        return mergeFrom((de.tum.i13.bandency.TopKStreaks)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.tum.i13.bandency.TopKStreaks other) {
      if (other == de.tum.i13.bandency.TopKStreaks.getDefaultInstance()) return this;
      if (other.getBucketFrom() != 0) {
        setBucketFrom(other.getBucketFrom());
      }
      if (other.getBucketTo() != 0) {
        setBucketTo(other.getBucketTo());
      }
      if (other.getBucketPercent() != 0) {
        setBucketPercent(other.getBucketPercent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.tum.i13.bandency.TopKStreaks parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.tum.i13.bandency.TopKStreaks) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bucketFrom_ ;
    /**
     * <pre>
     *begin of the bucket
     * </pre>
     *
     * <code>int32 bucket_from = 1;</code>
     * @return The bucketFrom.
     */
    public int getBucketFrom() {
      return bucketFrom_;
    }
    /**
     * <pre>
     *begin of the bucket
     * </pre>
     *
     * <code>int32 bucket_from = 1;</code>
     * @param value The bucketFrom to set.
     * @return This builder for chaining.
     */
    public Builder setBucketFrom(int value) {
      
      bucketFrom_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *begin of the bucket
     * </pre>
     *
     * <code>int32 bucket_from = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBucketFrom() {
      
      bucketFrom_ = 0;
      onChanged();
      return this;
    }

    private int bucketTo_ ;
    /**
     * <pre>
     *end of the bucket
     * </pre>
     *
     * <code>int32 bucket_to = 2;</code>
     * @return The bucketTo.
     */
    public int getBucketTo() {
      return bucketTo_;
    }
    /**
     * <pre>
     *end of the bucket
     * </pre>
     *
     * <code>int32 bucket_to = 2;</code>
     * @param value The bucketTo to set.
     * @return This builder for chaining.
     */
    public Builder setBucketTo(int value) {
      
      bucketTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *end of the bucket
     * </pre>
     *
     * <code>int32 bucket_to = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBucketTo() {
      
      bucketTo_ = 0;
      onChanged();
      return this;
    }

    private int bucketPercent_ ;
    /**
     * <pre>
     *round(float, 3) * 1000 as integer
     * </pre>
     *
     * <code>int32 bucket_percent = 3;</code>
     * @return The bucketPercent.
     */
    public int getBucketPercent() {
      return bucketPercent_;
    }
    /**
     * <pre>
     *round(float, 3) * 1000 as integer
     * </pre>
     *
     * <code>int32 bucket_percent = 3;</code>
     * @param value The bucketPercent to set.
     * @return This builder for chaining.
     */
    public Builder setBucketPercent(int value) {
      
      bucketPercent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *round(float, 3) * 1000 as integer
     * </pre>
     *
     * <code>int32 bucket_percent = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBucketPercent() {
      
      bucketPercent_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Challenger.TopKStreaks)
  }

  // @@protoc_insertion_point(class_scope:Challenger.TopKStreaks)
  private static final de.tum.i13.bandency.TopKStreaks DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.tum.i13.bandency.TopKStreaks();
  }

  public static de.tum.i13.bandency.TopKStreaks getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopKStreaks>
      PARSER = new com.google.protobuf.AbstractParser<TopKStreaks>() {
    @java.lang.Override
    public TopKStreaks parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TopKStreaks(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TopKStreaks> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TopKStreaks> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.tum.i13.bandency.TopKStreaks getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

